update_tools some output cosmetics.
Some better distinguishable sections; it is now more clear to see in
which tool chain we are.

diff --git a/bin/update_tools b/bin/update_tools
--- a/bin/update_tools
+++ b/bin/update_tools
@@ -8,6 +8,7 @@ brew_update() {
 
 
 brew_check_for_updates() {
+    print_start_tool_update "HomeBrew"
     brew update
     echo
     echo cask
@@ -17,18 +18,49 @@ brew_check_for_updates() {
 
 
 composer_update() {
+    print_start_tool_update "Composer"
     composer global update
 }
 
 
 vim_update() {
-    cd "$HOME"/.vim/ || (echo 'CANNOT CD TO VIM DIRECTORY' && exit 1)
+    print_start_tool_update "Vim"
+    cd "$HOME"/.vim/ || print_error_and_exit 'CANNOT CD TO VIM DIRECTORY'
     ./update
 }
 
 
-pushd "$(pwd)" || (echo 'CANNOT PUSH WORKING DIR TO THE DIRSTACK' && exit 1)
+print_error_and_exit() {
+    local message=$1
+    echo
+    echo "*** ERROR ***"
+    printf "*** %s" "$message"
+    echo
+    exit 1
+}
+
+
+underline() {
+    local tool=$1
+    local char=$2
+    if [[ "$char" == "" ]]; then
+        char='='
+    fi
+    python -c "print('$char' * ${#tool})"
+}
+
+
+print_start_tool_update() {
+    local tool=$1
+    echo
+    underline "$tool"
+    echo "$tool"
+    underline "$tool"
+}
+
+
+pushd "$(pwd)" || print_error_and_exit 'CANNOT PUSH WORKING DIR TO THE DIRSTACK'
 composer_update
 vim_update
 brew_check_for_updates
-popd || (echo 'CANNOT POP FROM DIRSTACK' && exit 1)
+popd || print_error_and_exit 'CANNOT POP FROM DIRSTACK'
