Take Python Virtual environments into account if possible
When a virtualenv exists, `project_goto` (renamed from `goto_project` in
line with all the ssh_* functions) will try to activate it.
This is more POC than a robust solution, but does the basic thing it
should do; deactivate the current virtualenv and activate the new one
(if either one is present).
The solution might be done cleaner, for instance now; it will deactivate
and reactivate the virtualenv, even if the one requested to be activated
was already activated before, etc... but it works fine enough for the
time being.

The 1-1 mapping of project name and virtualenv could make some
virtualenvs rather long in name, since at work we prefix this with the
names of the technology in use and what not, but since Python is not
used that much at work, it's fine I guess.  Also, if the virtualenv is
named the same as the project, it eliminates confusion... It _does_ make
a very long prompt though :)

Closes #37

diff --git a/.bash/functions b/.bash/functions
--- a/.bash/functions
+++ b/.bash/functions
@@ -99,16 +99,27 @@ ssh_user() {
 # Change to a project directory quickly.
 # If no argument was given, use FZF to select one.
 #
-goto_project() {
+project_goto() {
     local project=$1
     if [[ "$project" == "" ]]
     then
         project=$(find "$DIR_PROJECTS" -type d -maxdepth 1 | cut -d/ -f5 | $FZF_PREVIEW "ls $DIR_PROJECTS/{}")
     fi
-    if [[ "$project" != "" ]]
+    if [[ "$project" == "" ]] || [[ ! -d "$DIR_PROJECTS"/"$project" ]]
     then
-        cd "$DIR_PROJECTS"/"$project" || return
+        echo "Project not found in [$DIR_PROJECTS]"
+        return 1
     fi
+    cd "$DIR_PROJECTS"/"$project" || return 1
+    if type "deactivate" > /dev/null 2>&1
+    then
+        deactivate
+    fi
+    if [[ -d "$DIR_VIRTUALENVS"/"$project" ]]
+    then
+        . "$DIR_VIRTUALENVS"/"$project"/bin/activate
+    fi
+    return 0
 }
 
 
